version: '2.0'

services:

  db:
    image: postgres
    restart: always
    hostname: db
    ports:
      - 10001:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: Pwr-fhs-dev

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 10000:8080

  fault-handling-system:
    image: fault-handling-system
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - 8080:80
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    volumes:
      - ./appsettings.json:/Fault-handling-system/appsettings.json
      - attachments:/Fault-handling-system/attachments
volumes:
  attachments:
