version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: Pwr-fhs-dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080
